langage: node_js
node_js:
  - "10"
jobs:
  include:
    - stage: deploy
      deploy:
        provider: heroku
        api-key:
           secure: $HEROKU_API_KEY
        app: crud-angular
        
    
  