langage: node_js
node_js:
  - "10"
before_script:
  - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

jobs:
  include:
    - stage: clean
      script:
        - ssh -o StrictHostKeyChecking=no lawliet@192.168.32.128
        - ls
    
          
    
  