langage: java
jdk:
  - "oraclejdk8"
jobs:
  include:
    - stage: clean
      script:
        - cd crud-angular
        - mvn clean
    - stage: build
      script:
        - cd crud-angular
        - mvn install
    - stage: deploy
      deploy:
        provider: heroku
        api-key:
           secure: $HEROKU_API_KEY
        app: crud-angular 
          
    
  