langage: python
python:
  - "2.7"
jobs:
  include:
    - stage: check
      script:
        - pip install ansible
        - ansible --version
        - ansible-playbook -vvv playbook.yml -u lawliet
    
  