langage: node_js
node_js:
  - "10"
jobs:
  include:
    - stage: clean
      script:
        - cd crud-angular
        - "cp settings.xml $HOME/.m2/settings.xml"
        - mvn clean deploy --settings /home/travis/settings.xml -Dmaven.test.skip=true
    

          
    
  