---
- hosts: ubuntu
  remote_user: lawliet
  tasks:
    - name: Remove file
      file:
        path: test.txt
        state: absent
      wait_for_connection:
        delay: 60
        timeout: 300
...
